import {
  BadgeDollarSign,
  Beef,
  BookOpen,
  Bus,
  Camera,
  CircleDollarSign,
  Clapperboard,
  CreditCard,
  Droplets,
  Dumbbell,
  Gem,
  Gift,
  HandCoins,
  HeartPulse,
  Home,
  Laptop,
  PiggyBank,
  Popcorn,
  Receipt,
  Scale,
  Shirt,
  ShieldPlus,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tv,
  Utensils,
  Wallet,
  WashingMachine,
  Wifi,
  Youtube,
  Coins,
} from "lucide-react"

const DEFAULT_ICON = Wallet
const DEFAULT_TINT = {
  bg: "#f6efe5",
  color: "#6b5b4f",
}

const CATEGORY_ICONS = {
  "Transportasi": Bus,
  "Sedekah": HandCoins,
  "Elektronik": Laptop,
  "Healthcare": HeartPulse,
  "Utang": Scale,
  "Body Care": Sparkles,
  "Musibah": ShieldPlus,
  "Kondangan": Gift,
  "Makan di luar": Utensils,
  "Makan di rumah": Beef,
  "Hiburan": Clapperboard,
  "Jajan": Popcorn,
  "Skincare": Sparkles,
  "Belanja": ShoppingBag,
  "Laundry": WashingMachine,
  "Ilmu": BookOpen,
  "Pakaian": Shirt,
  "Tabungan Cash": PiggyBank,
  "Tagihan": Receipt,
  "Monthly Salary": BadgeDollarSign,
  "Insentif": Coins,
  "Reimbursement": CreditCard,
  "Pemberian": Gift,
  "THR": Gift,
  "Emas": Gem,
  "Saham": CircleDollarSign,
}

const BILL_ICONS = {
  "Listrik": Receipt,
  "Air (PDAM)": Droplets,
  "Internet/WiFi": Wifi,
  "Pulsa & Data": Smartphone,
  "BPJS Kesehatan": Stethoscope,
  "BPJS Ketenagakerjaan": ShieldPlus,
  "Asuransi": ShieldPlus,
  "Sewa Rumah": Home,
  "Cicilan/Kredit": CreditCard,
  "Netflix": Tv,
  "Spotify": Camera,
  "YouTube Premium": Youtube,
  "Gym": Dumbbell,
  "Arisan": HandCoins,
  "Other": Receipt,
}

const CATEGORY_TINTS = {
  warm: { bg: "#fbf0e9", color: "#c47d5a" },
  olive: { bg: "#f4f6ec", color: "#7c8c5a" },
  sage: { bg: "#ebf3f0", color: "#5b8c7a" },
  violet: { bg: "#f3effc", color: "#7c5fcf" },
  amber: { bg: "#fdf7e8", color: "#d4a853" },
  clay: { bg: "#f6efe5", color: "#8c7b6a" },
}

const CATEGORY_TINT_LOOKUP = {
  "Transportasi": "warm",
  "Sedekah": "olive",
  "Elektronik": "violet",
  "Healthcare": "sage",
  "Utang": "warm",
  "Body Care": "violet",
  "Musibah": "amber",
  "Kondangan": "amber",
  "Makan di luar": "warm",
  "Makan di rumah": "olive",
  "Hiburan": "violet",
  "Jajan": "amber",
  "Skincare": "violet",
  "Belanja": "warm",
  "Laundry": "clay",
  "Ilmu": "sage",
  "Pakaian": "warm",
  "Tabungan Cash": "sage",
  "Tagihan": "clay",
  "Monthly Salary": "olive",
  "Insentif": "sage",
  "Reimbursement": "violet",
  "Pemberian": "amber",
  "THR": "amber",
  "Emas": "amber",
  "Saham": "violet",
  "Listrik": "amber",
  "Air (PDAM)": "sage",
  "Internet/WiFi": "violet",
  "Pulsa & Data": "warm",
  "BPJS Kesehatan": "sage",
  "BPJS Ketenagakerjaan": "olive",
  "Asuransi": "olive",
  "Sewa Rumah": "clay",
  "Cicilan/Kredit": "warm",
  "Netflix": "violet",
  "Spotify": "sage",
  "YouTube Premium": "warm",
  "Gym": "olive",
  "Arisan": "amber",
  "Other": "clay",
}

export function getCategoryVisual(name) {
  return {
    icon: CATEGORY_ICONS[name] || DEFAULT_ICON,
    tint: CATEGORY_TINTS[CATEGORY_TINT_LOOKUP[name]] || DEFAULT_TINT,
  }
}

export function getBillVisual(name) {
  return {
    icon: BILL_ICONS[name] || CATEGORY_ICONS[name] || DEFAULT_ICON,
    tint: CATEGORY_TINTS[CATEGORY_TINT_LOOKUP[name]] || DEFAULT_TINT,
  }
}
