/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin")

module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Semantic tokens (read from CSS vars defined in globals.css)
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        'surface-warm': 'var(--surface-warm)',
        border: 'var(--border)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        income: 'var(--income)',
        expense: 'var(--expense)',
        savings: 'var(--savings)',
        primary: 'var(--primary)',
        'primary-deep': 'var(--primary-deep)',
        smart: 'var(--smart)',
        'smart-bg': 'var(--smart-bg)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        'hero-bg': 'var(--hero-bg)',
        'hero-mid': 'var(--hero-mid)',
        'hero-light': 'var(--hero-light)',

        // Earth (neutral / surface)
        earth: {
          50: '#FBF8F1',
          100: '#F3ECE2',
          200: '#E2D9CC',
          300: '#C8BEB1',
          400: '#897F75',
          500: '#7A7168',
          600: '#6B625A',
          700: '#5B534C',
          800: '#403831',
          900: '#29231E',
          950: '#211C18',
        },
        // MD3 color roles (CSS vars from globals.css). Namespaced under md3 so the
        // legacy semantic keys above keep their meaning until the Batch E sweep.
        md3: {
          primary: 'var(--md-sys-color-primary)',
          'on-primary': 'var(--md-sys-color-on-primary)',
          'primary-container': 'var(--md-sys-color-primary-container)',
          'on-primary-container': 'var(--md-sys-color-on-primary-container)',
          secondary: 'var(--md-sys-color-secondary)',
          'on-secondary': 'var(--md-sys-color-on-secondary)',
          'secondary-container': 'var(--md-sys-color-secondary-container)',
          'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
          tertiary: 'var(--md-sys-color-tertiary)',
          'on-tertiary': 'var(--md-sys-color-on-tertiary)',
          'tertiary-container': 'var(--md-sys-color-tertiary-container)',
          'on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
          error: 'var(--md-sys-color-error)',
          'on-error': 'var(--md-sys-color-on-error)',
          'error-container': 'var(--md-sys-color-error-container)',
          'on-error-container': 'var(--md-sys-color-on-error-container)',
          surface: 'var(--md-sys-color-surface)',
          'surface-container-lowest': 'var(--md-sys-color-surface-container-lowest)',
          'surface-container-low': 'var(--md-sys-color-surface-container-low)',
          'surface-container': 'var(--md-sys-color-surface-container)',
          'surface-container-high': 'var(--md-sys-color-surface-container-high)',
          'surface-container-highest': 'var(--md-sys-color-surface-container-highest)',
          'on-surface': 'var(--md-sys-color-on-surface)',
          'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
          outline: 'var(--md-sys-color-outline)',
          'outline-variant': 'var(--md-sys-color-outline-variant)',
          'inverse-surface': 'var(--md-sys-color-inverse-surface)',
          'inverse-on-surface': 'var(--md-sys-color-inverse-on-surface)',
          'inverse-primary': 'var(--md-sys-color-inverse-primary)',
        },
        // Cream (backgrounds)
        cream: {
          50: '#FBF8F1',
          100: '#F7F1E8',
          200: '#EFE7DB',
        },
        // Sage (income / positive)
        sage: {
          50: '#EEF6F1',
          100: '#E5F0EB',
          200: '#C8DED3',
          300: '#9EC2AE',
          400: '#4F876D',
          500: '#2F6B57',
          600: '#255344',
          700: '#1D4538',
          main: '#2F6B57',
          light: '#8EB5A5',
          deep: '#255344',
        },
        // Clay (expense / warm)
        clay: {
          50: '#FCF0ED',
          100: '#F6D8D1',
          200: '#E9B6AA',
          300: '#CB796B',
          400: '#A45343',
          500: '#883F34',
          600: '#71352C',
          main: '#B9695B',
          light: '#CB796B',
          deep: '#883F34',
        },
        // Moss (savings / growth)
        moss: {
          50: '#EDF5F3',
          100: '#E2F0ED',
          200: '#C4DED9',
          300: '#94C4BC',
          400: '#4F8C83',
          500: '#2D6A62',
          600: '#24574F',
          main: '#2D6A62',
          light: '#8FBAB2',
          deep: '#24574F',
        },
        // Violet (smart / Pro)
        violet: {
          50: '#F3F0FB',
          100: '#EAE4F7',
          200: '#D6CDEE',
          300: '#B9AADE',
          400: '#8A77C8',
          500: '#6E59B5',
          600: '#584494',
          700: '#473777',
          800: '#392D60',
          900: '#2C2349',
          soft: '#EAE4F7',
          main: '#6E59B5',
          deep: '#584494',
        },
        // Amber (warning / highlight)
        amber: {
          50: '#FFF7E1',
          100: '#FFEAB0',
          200: '#F6D37A',
          300: '#E8B44B',
          400: '#8A5A00',
          500: '#6B4400',
          main: '#8A5A00',
          light: '#E8B44B',
        },
        // Rose (danger / accent)
        rose: {
          50: '#FCEAEA',
          100: '#F6C8C8',
          200: '#EBA0A0',
          300: '#D86E6E',
          400: '#B33A3A',
          500: '#902D2D',
          main: '#B33A3A',
          light: '#D86E6E',
        },
        // Indigo (secondary action)
        indigo: {
          50: '#EDF3F8',
          100: '#D7E4EF',
          200: '#B1CADB',
          300: '#87A9C0',
          400: '#5B7F9A',
          500: '#3F6480',
          main: '#5B7F9A',
          deep: '#3F6480',
        },
      },
      fontFamily: {
        display: ['var(--font-display)', 'serif'],
        body: ['var(--font-body)', 'sans-serif'],
      },
      animation: {
        'float': 'none',
        'fade-in-up': 'fadeIn var(--motion-control) var(--ease-out) both',
        'fade-in': 'fadeIn var(--motion-control) var(--ease-out) both',
        'slide-down': 'slideDown var(--motion-sheet) var(--ease-drawer) both',
        'count-in': 'fadeIn var(--motion-control) var(--ease-out) both',
        'bento-in': 'bentoIn var(--motion-control) var(--ease-out) both',
        'glow-pulse': 'none',
        'shimmer': 'shimmer 2.4s linear infinite',
        'scale-in': 'scaleIn var(--motion-control) var(--ease-out) both',
        'slide-up': 'slideUp var(--motion-sheet) var(--ease-drawer) both',
        'gradient-shift': 'none',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        fadeInUp: {
          'from': { opacity: '0', transform: 'translateY(16px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          'from': { opacity: '0' },
          'to': { opacity: '1' },
        },
        slideDown: {
          'from': { opacity: '0', transform: 'translateY(-16px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          'from': { opacity: '0', transform: 'translateY(24px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        countIn: {
          'from': { opacity: '0', transform: 'scale(0.95)' },
          'to': { opacity: '1', transform: 'scale(1)' },
        },
        bentoIn: {
          'from': { opacity: '0' },
          'to': { opacity: '1' },
        },
        glowPulse: {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        scaleIn: {
          'from': { opacity: '0', transform: 'scale(0.92)' },
          'to': { opacity: '1', transform: 'scale(1)' },
        },
        gradientShift: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
      },
      boxShadow: {
        'warm': '0 4px 16px rgba(41,35,30,0.06)',
        'warm-lg': '0 8px 32px rgba(41,35,30,0.1)',
        'warm-xl': '0 16px 48px rgba(41,35,30,0.12)',
        'glass': '0 8px 32px rgba(41,35,30,0.08), inset 0 1px 0 rgba(255,255,255,0.5)',
        'inset-light': 'inset 0 1px 0 rgba(255,255,255,0.6), inset 0 -1px 0 rgba(0,0,0,0.04)',
        'pop': '0 12px 40px rgba(47,107,87,0.18)',
        'pop-lg': '0 20px 60px rgba(47,107,87,0.22)',
        'smart': '0 12px 40px rgba(110,89,181,0.18)',
        'smart-lg': '0 20px 60px rgba(110,89,181,0.22)',
      },
      transitionDuration: {
        press: '130ms',
        control: '180ms',
        sheet: '300ms',
        education: '400ms',
      },
      transitionTimingFunction: {
        out: 'cubic-bezier(0.16, 1, 0.3, 1)',
        drawer: 'cubic-bezier(0.32, 0.72, 0, 1)',
      },
      backdropBlur: {
        'xs': '2px',
        '2xl': '32px',
        '3xl': '48px',
      },
    },
  },
  plugins: [
    plugin(function ({ addVariant }) {
      addVariant("can-hover", "@media (hover: hover) and (pointer: fine)")
    }),
  ],
}
